version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tatsumaki-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
